4024 - Implement HoloFuel MVP v.0.1.3 UI design - Transaction History
Holo-Host/hp-admin pull request #156
Opened 2020-01-03 22:05 UTC by robbiecarlton

2020-01-06 22:36 UTC, JettTech requested changes
The updates here look good; however, I noticed that the null state pages are not implemented.  Can you please include those, and ping for another review?  Almost there! :)

2020-01-06 22:36 UTC, JettTech commented on src/holofuel/components/SideMenu/SideMenu.js
> +            <Link to='/admin/' styleName='nav-link'>
This leads to an empty page, which will cause the app to break when served via HoloScape and will not connect properly in Holochain contexts.  

For now, I think we can leave this as is and update it whenever we do our build compatibility between holochain and holo contexts.  One thing I would like to discuss is using hash routing (ie: `<Link to='/#admin/' styleName='nav-link'>`), which might help avoid collision between contexts...

2020-01-06 22:36 UTC, JettTech commented on src/holofuel/pages/TransactionHistory/TransactionHistory.js
>      </div>}
Let's update the styles for the null state page as well.

2020-01-07 19:39 UTC, JettTech approved these changes
LGTM

2020-01-07 20:12 UTC, robbiecarlton commented on src/holofuel/components/SideMenu/SideMenu.js
> +            <Link to='/admin/' styleName='nav-link'>
This link just shouldn't appear outside of `hp-admin` context, so that's part of a broader issue we need to figure out.

2020-01-07 20:12 UTC, merged