Updated the holochainClient to make one WebSocket Connection
Holo-Host/hp-admin pull request #157
Opened 2020-01-04 03:57 UTC by zo-el

2020-01-27 17:03 UTC, JettTech approved these changes
LGTM. Thanks for updating this. :tada:  

Also, happy to leave the error catch to 10 tries/call for now, but let's talk about this and see if there is an optimal number.

2020-01-27 18:43 UTC, robbiecarlton requested changes

2020-01-27 18:43 UTC, robbiecarlton commented on src/holochainClient.js
> +  }
isn't this equivalent to
```
if (hcFlag) {
  await wait(1000)
  hcFlag = false
}
```
?

2020-01-27 18:43 UTC, robbiecarlton commented on src/holochainClient.js
> +async function init () {
on the fence about this, but I think I'd prefer this be called `initHolochainClient`.

It makes the specific difference between the two functions clearer.

2020-01-27 18:43 UTC, robbiecarlton commented on src/holochainClient.js
> +let hcFlag = false
can we call this something more descriptive?

`isInitiatingHcConnection` or similar

2020-01-27 18:43 UTC, robbiecarlton commented on package.json
> +    "test:ci": "CI=1 npm run test:unit",
😆 I feel like we make this change all the time and somehow it never sticks

2020-01-27 20:00 UTC, robbiecarlton commented on src/holochainClient.js
> +  }
oh, I get it.

Going to think about if there's a more readable way to do this.

2020-01-29 20:16 UTC, robbiecarlton requested changes
One more change request, then it's good to merge 👍

2020-01-29 20:16 UTC, robbiecarlton commented on src/holochainClient.js
> +  while (isInitiatingHcConnection) {
can we add a comment calling out that this variable is being changed in a different function running in parallel?

2020-01-30 23:15 UTC, robbiecarlton approved these changes

2020-02-21 20:31 UTC, merged