(wip) 7847 - HoloFuel CleanUp Items
Holo-Host/hp-admin pull request #168
Opened 2020-01-15 22:03 UTC by robbiecarlton

2020-01-17 02:17 UTC, JettTech requested changes
Overall, looks good!  Glad to see the `isPayingARequest` update.  

There is one change we should make to avoid the app opening onto an empty page for the holochain  (& thereby holoscape) environments, but otherwise, I think these changes are straightforward. :+1:

2020-01-17 02:17 UTC, JettTech commented on src/holofuel/HFRouter.js
>      <Route path='/holofuel' exact component={() => <Redirect to='/holofuel/' />} />
Let's add a route for the Holochain case, to make sure we still support HF testing in / use with Holoscape.  We could do something like the following:

`{process.env.REACT_APP_HOLOFUEL_APP === 'true' && <Route path='/' exact component={() => <Redirect to='/holofuel/' />} />}`

2020-01-17 02:17 UTC, JettTech commented on src/holofuel/HFRouter.test.js
> -  it('works with root url', () => {
We should probably still keep this case, for serving HF in Holochain contexts, like Holoscape.

2020-01-17 02:17 UTC, JettTech commented on src/graphql-server/schema.graphql
> +  isPayingARequest: Boolean
:+1:

2020-01-17 02:17 UTC, JettTech commented on src/data-interfaces/HoloFuelDnaInterface.js
> +  const isPayingARequest = !!event[2].Promise.request
Nice. Glad this solution worked as expected. :+1:

2020-01-17 02:17 UTC, JettTech commented on src/holofuel/pages/Inbox/Inbox.test.js
> +  .sort((a, b) => a.timestamp > b.timestamp ? -1 : 1)
Nice change.  I think I reflected this same change in my most recent PR too! :muscle: :100:

2020-01-17 18:03 UTC, robbiecarlton commented on src/holofuel/HFRouter.js
>      <Route path='/holofuel' exact component={() => <Redirect to='/holofuel/' />} />
Good call.
I forget about the Holoscape testing case.

2020-01-17 18:32 UTC, robbiecarlton commented on package.json
> +    "start:live": "rm -rf ./node_modules/.cache/babel-loader && REACT_APP_MOCK_DNA_CONNECTION='false' node scripts/start.js",
@JettTech NB this small update. Just standardizing the naming.

2020-01-17 18:33 UTC, robbiecarlton commented on src/holofuel/HFRouter.js
>      <Route path='/holofuel' exact component={() => <Redirect to='/holofuel/' />} />
because of the way the routers are nested, I could actually add it without the condition.

2020-01-22 01:22 UTC, JettTech requested changes
Ok.  I requested a simple update due to the script name changes.  Otherwise, your code looks good and unit tests pass.

2020-01-22 01:22 UTC, JettTech commented on package.json
>      "start:holofuel-mock": "REACT_APP_HOLOFUEL_APP=true npm run start-mock",
Due to the change in the names, lines 11 & 12 need ot have the script updated from `start-mock` and `start-live` to `start:mock` and `start:live`

2020-01-22 01:24 UTC, JettTech commented
FYI: In order to test manually, I updated the nix-config and created new agents so we can try live testing.  During my attempts to test in a two-agent scenario, I encountered extreme networking issues, to the point that I could only test this branch in a single agent environment.  0.0.42-alpha4 is *noticeably slower*. 

I don't think this level of testing is necessary for this ticket and therefore think this is good to ship as soon as the script names are updated. Nonetheless, I think it is important to note, and I will make a new ticket in our backlog to represent this need.

2020-01-22 04:58 UTC, robbiecarlton commented on package.json
>      "start:holofuel-mock": "REACT_APP_HOLOFUEL_APP=true npm run start-mock",
good catch

2020-01-22 04:59 UTC, merged