(WIP) 5526 - Hide empty partitions in Inbox
Holo-Host/hp-admin pull request #226
Opened 2020-03-25 22:54 UTC by robbiecarlton

2020-03-26 15:46 UTC, robbiecarlton commented
See comment with skipped test. @JettTech I spent some more time working on that test this morning with no luck and eventually agreed with @SirRobLyon that it was not worth more time to write a test for a cosmetic change that works in the app.

2020-03-26 21:05 UTC, JettTech requested changes
A few small updates and a question.  Let me know if you want to chat.

2020-03-26 21:05 UTC, JettTech commented on src/holofuel/pages/Inbox/Inbox.js
> +    }, 1000)
Can we return this to 5000ms?

2020-03-26 21:05 UTC, JettTech commented on src/holofuel/pages/Inbox/Inbox.js
> +        closeDrawer={() => setIsDrawerOpen(false)}
Replacing the knowledge of which transaction is open with a simple boolean, will allow multiple transactions to be open at once.  Even though this boolean is simpler to read, I do believe we need to restore this state knowledge.  (We had explicitly prevented the multiple drawer opening behavior during our UX iterations with Jamison last fall.)

2020-03-26 21:05 UTC, JettTech commented on src/holofuel/pages/Inbox/Inbox.test.js
> +import { DIRECTION } from '../../../models/Transaction'
This is a bit nit-picky, but let's replace the relative path with the absolute (from src), just to keep things clean and consistent.

2020-03-26 21:05 UTC, JettTech commented on src/holofuel/pages/Inbox/Inbox.test.js
> +      jest.runAllTimers()
:1st_place_medal: Yea!! Glad we're using this - this is gold!

2020-03-26 21:05 UTC, JettTech commented on src/pages/Dashboard/Dashboard.js
> +  const noInstalledHapps = 0
:+1:

2020-03-26 21:05 UTC, JettTech commented on src/holofuel/pages/Inbox/Inbox.test.js
> +    ]
Just to capture our conversation with this update, I'll write the overview decision about this testing pattern here.

> We decided that this approach is not optimal, but that we would keep this approach for now.  We are interested in finding a better testing design that would prevent multiple iterations of the same mock.

2020-03-26 21:05 UTC, JettTech commented on src/holofuel/pages/Inbox/Inbox.test.js
> +    // feature that works
Is there a ticket in PT to capture this?

2020-03-26 21:05 UTC, JettTech commented on src/holofuel/pages/Inbox/Inbox.js
> +  const [hiddenTransactionIds, setHiddenTransactionIds] = useState([])
What is the benefit of adding this additional layer of component abstraction?

2020-03-27 16:46 UTC, robbiecarlton commented on src/holofuel/pages/Inbox/Inbox.js
> +  const [hiddenTransactionIds, setHiddenTransactionIds] = useState([])
answered in person

2020-03-27 19:08 UTC, JettTech commented
@robbiecarlton - Tests run and all looks well.  

Before merging, however, I would like to demo the change to the drawer UX with Rob and C to ensure that this matches their approval too.  If they approve the UX change, then I'm fine with the merge.

2020-03-27 20:59 UTC, JettTech approved these changes
LGTM!

2020-03-27 22:11 UTC, merged