B 01172 zome calls
Holo-Host/hp-admin pull request #322
Opened 2020-08-03 07:10 UTC by JettTech

### Updates;
 - plugs in zome call endpoint

2020-08-04 21:26 UTC, robbiecarlton requested changes
One small change, otherwise good to go.

2020-08-04 21:26 UTC, robbiecarlton commented on src/mock-dnas/hpos.js
> +              values: [10, 40, 20, 30]
Only change I would make is to not mock any data we're not using. It just creates debt. If we need this extra data later we can just add it to the mocks at that time

2020-08-05 13:26 UTC, robbiecarlton approved these changes

2020-08-05 13:36 UTC, zo-el approved these changes

2020-08-05 14:23 UTC, JettTech commented
nb: Tests fail on ci due to memory, but pass locally.

2020-08-05 14:23 UTC, merged