B 02101
Holo-Host/hp-admin pull request #343
Opened 2020-09-14 13:13 UTC by JettTech

### Upates:
 - adds puppeteer setup for holo e2e tests
 - adds tryorama setup fo rholo e2e tests
 - adds tests to sign in and log out
 - adds zome call test

2020-09-21 02:34 UTC, robbiecarlton requested changes
A couple of code cleanup changes here.

But also, 

`test:integration-holo` and `test:integration-holochain` are failing for me locally, and tests and linter are failing on CI.

2020-09-21 02:34 UTC, robbiecarlton commented on package.json
> +    "serve-test": "PORT=3100 npm run start:holofuel-holo-live",
can we remove `test:integration-with-setup ` command now? Or is that still relevant?

2020-09-21 02:34 UTC, robbiecarlton commented on package.json
> +    "@holochain/tryorama": "file:/home/lisa/Documents/gitrepos/holochain/holochain-old/tryorama",
Can this be replaced with current Tryorama? Can't merge with this.

2020-09-21 02:34 UTC, robbiecarlton commented on nixpkgs.nix
> +  # commit: 6506590fc254932b4a3b9ba5c9f965c042ab2941
remove comment

2020-09-21 02:34 UTC, robbiecarlton commented on .env.example
> +REACT_APP_DNA_PATH=/[Path]/[to]/[holofuel]/[repo]/.dna.json
Doesn't look like you're using this env variable anymore

2020-09-21 02:34 UTC, robbiecarlton commented on package.json
> +    "refresh": "npm run hc:stop; npm run sim2h-server:clear; npm run hc:clean-storage",
I find `refresh` a little misleading. Maybe `stop-all`?

2020-09-21 02:34 UTC, robbiecarlton commented on scripts/wait-for-conductor.js
> +        // console.log('>>>>>> CALL TO CONDUCTOR DID NOT PASS :: error code : ', error.code)
is this still supposed to be commented out?

2020-09-21 02:34 UTC, robbiecarlton commented on src/holofuel/components/layout/PrimaryLayout/PrimaryLayout.module.css
> +/* connection text #389ea6 */
remove comment

2020-09-21 02:34 UTC, robbiecarlton commented on holoIntegration-setup/setup.js
> +const HAPP_URL = 'http://testfuel.holo.host/'
This variable isn't being used

2020-09-21 02:34 UTC, robbiecarlton commented on holoIntegration-setup/teardown.js
> +const DIR = path.join(os.tmpdir(), 'jest_puppeteer_global_setup');
Would be more robust to import this from the other file.

2020-09-21 06:18 UTC, JettTech commented on package.json
> +    "@holochain/tryorama": "file:/home/lisa/Documents/gitrepos/holochain/holochain-old/tryorama",
This currently needs to be run with a specific build of tryorama (off of branch`2020-08-31/hosted-consistency`).  Until that PR is merged, you will need to pull down a local copy and point to your local path.

2020-09-21 06:24 UTC, JettTech commented
NOTE: Locally, with a copy of tryorama built off of branch`2020-08-31/hosted-consistency`, both linting and tests pass. We wll need to await [Tryorama PR #36](https://github.com/holochain/tryorama/pull/36) to be merged in order for CI to properly run tests.

2020-09-21 06:26 UTC, JettTech commented
@robbiecarlton - This PR is *only* for e2e holo hosting tests, not holochain.  

Also, please read the updated description for how to run to the tests, and let me know if you still run into issues running the holo integration tests

2020-09-21 06:30 UTC, JettTech commented on package.json
> +    "serve-test": "PORT=3100 npm run start:holofuel-holo-live",
We can.  This PR does not work on the holochain integration tests, so the work on those remains untouched in this version. That said, this script is deprecated, so I am on board with removing it anyway.

2020-09-21 19:48 UTC, zippy commented on src/holofuel/__integration_tests__/holo/CreateRequest.holoIntegration.test.js
> +      expect(listPending.requests.length).toEqual(1)
I think we should add a zome call check before the request that calls checkListPending and ensures that the length is 0.

2020-09-21 19:49 UTC, zippy approved these changes

2020-09-21 19:56 UTC, zippy approved these changes
This is fantastic work.  Definitely good-enough for us to build from for when we get the rsm-context working.

One tiny request is to have a "before check" on the CreateRequest test that shows proves the transition from 0 to 1 items in list pending.

Also I want to note that we are going to have to do some work with these tests that use HostedPlayer in making sure that the initial state is clean.  I would eventually like to be able to run this test from inside final-exam, but I don't think that's currently possible because there are hard references to the active holoport, i.e. they all seem to use Joel's holoport TEST_HOST[0].  I think a next step would be for the test runner to fully spawn an hpos-shell that it uses for the test, not a holoport.  But that should happen as a followup.

2020-09-21 20:24 UTC, zo-el approved these changes

2020-09-22 18:16 UTC, robbiecarlton requested changes
Tests and linter still failing on CI.

Not sure why linter is failing, tests most likely failing because of the `file:` setting for the Tryorama dependency in `package.json`.

Since we're not planning on running the E2E tests in this CI, my recommendation is that you just put in a normal version constraint for Tryorama in `package.json`, so that CI tests pass and `npm i` works when downloading the repo.

The`README.md` instructions explains how to update the Tryorama thing.

A couple of other change request:

Could you add a .gitignore file inside `src/holofuel/__integration_tests__/holo/snapshots` so that the directory gets committed?

And could you get package-lock.json back?

If you just use the one in develop and then it might pick up a small change from installing Tryorama.

These changes plus once I've successfully run the tests locally and we're good to go

2020-09-22 20:26 UTC, robbiecarlton requested changes

2020-09-22 20:26 UTC, robbiecarlton commented on src/holochainClient.js
> +export const CHAPERONE_SERVER_URL = CHAPERONE_SERVER.test
this should branch based on an environment variable right? We don't want `CHAPERONE_SERVER_URL = CHAPERONE_SERVER.test` in production.

Might be simplest to just have a `REACT_APP_CHAPERONE_SERVER_URL`  environment variable and not have these hard coded values at all.

2020-09-28 18:53 UTC, robbiecarlton commented on .gitignore
> +src/holofuel/__integration_tests__/holo/snapshots/*
@JettTech This doesn't mean the directory is committed. You have to add a .gitignore file to the directory you want to be committed, so `src/holofuel/__integration_tests__/holo/snapshots/` in this case.

2020-09-28 19:02 UTC, robbiecarlton commented on src/holofuel/__integration_tests__/holo/snapshots/.gitignore
> +!.gitignore
@JettTech - adding this file means that the snapshots directory will be created when you check out this branch, but nothing in the directory (except this file itself) will be committed

2020-09-28 19:03 UTC, robbiecarlton commented on .gitignore
> -src/holofuel/__integration_tests__/holo/snapshots/*
@JettTech - this line won't actually create the snapshots directory. See the `.gitignore` file I added for an example of a way to do that.

2020-09-28 19:03 UTC, robbiecarlton approved these changes

2020-09-29 16:02 UTC, merged