4705 holofuel data layer updated
Holo-Host/hp-admin pull request #46
Opened 2019-09-10 03:25 UTC by JettTech

Updates the HF data layer to include the following updates : 
 - whoami endpoint updates - now accepts an opt. agentId (aka. agent pubkey) param that will return the matching nick
- accept_request gql query - now calls the updated dna endpoint 'accept_requests_pending', which officially accepts the origin hash as the id
- resulting_balance key within adjustment obj is mocked for each transaction returned from list_transactions endpoint.  This is currently a WIP in the DNA.

2019-09-10 18:04 UTC, robbiecarlton requested changes

2019-09-10 18:04 UTC, robbiecarlton commented on src/data-interfaces/HoloFuelDnaInterface.js
> +      await createZomeCall('transactions/receive_payments_pending')({ origin: transactionId })
Doesn't the param need to be an array?

Looking at the HF PR it looks like the call should look like `({ promises: [transactionId] })`.

2019-09-10 18:04 UTC, robbiecarlton commented on src/data-interfaces/__mocks__/HoloFuelInterface.js
> +    fees: fees || 0,
we typically don't want to provide defaults for these as they will overwrite the cache. Can explain more on our call today.

2019-09-10 19:09 UTC, robbiecarlton commented on src/data-interfaces/HoloFuelDnaInterface.js
> +  const parsedAdjustment = adjustmentValues.reduce((result, field, index) => {
you can use `lodash.mapValues here`

something like 
`import { mapValues} from 'lodash/fp'` <-- note the fp

`const parsedAdjustment = mapValues('Ok', object)`

or if that doesn't work

`const parsedAdjustment = mapValues(key => key.Ok, object)`

2019-09-10 19:25 UTC, JettTech commented on src/data-interfaces/HoloFuelDnaInterface.js
> +      await createZomeCall('transactions/receive_payments_pending')({ origin: transactionId })
Good thought. It actually is an param enum that can accepts either an array or a single hashString.
```
pub enum ListOrigins {
    Single(Address),
    Multiple(Vec<Address>),
}
```

2019-09-11 14:25 UTC, JettTech commented on src/data-interfaces/__mocks__/HoloFuelInterface.js
> +    fees: fees || 0,
Just for completion tot his comment, we discussed that this is generally an anti-pattern for Apollo in the DNA Interfaces, but not a problem in the DNA Interface **mocks**, as it doesn't affect the store / cache. I will go ahead and leave this one be.

2019-09-11 14:44 UTC, merged